# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bamboo_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import franka_controller_pb2 as franka__controller__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62\x61mboo_service.proto\x12\x06\x62\x61mboo\x1a\x17\x66ranka_controller.proto\"\x13\n\x11RobotStateRequest\"\\\n\rTimedWaypoint\x12\'\n\x08waypoint\x18\x01 \x01(\x0b\x32\x15.FrankaControlMessage\x12\x10\n\x08\x64uration\x18\x02 \x01(\x01\x12\x10\n\x08velocity\x18\x03 \x03(\x01\"\x7f\n\x1fJointImpedanceTrajectoryRequest\x12(\n\twaypoints\x18\x01 \x03(\x0b\x32\x15.bamboo.TimedWaypoint\x12\x18\n\x10\x64\x65\x66\x61ult_duration\x18\x02 \x01(\x01\x12\x18\n\x10\x64\x65\x66\x61ult_velocity\x18\x03 \x03(\x01\"\x12\n\x10TerminateRequest2\xff\x01\n\x14\x42\x61mbooControlService\x12\x44\n\rGetRobotState\x12\x19.bamboo.RobotStateRequest\x1a\x18.FrankaRobotStateMessage\x12\x62\n\x1f\x45xecuteJointImpedanceTrajectory\x12\'.bamboo.JointImpedanceTrajectoryRequest\x1a\x16.FrankaCommandResponse\x12=\n\tTerminate\x12\x18.bamboo.TerminateRequest\x1a\x16.FrankaCommandResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bamboo_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROBOTSTATEREQUEST']._serialized_start=57
  _globals['_ROBOTSTATEREQUEST']._serialized_end=76
  _globals['_TIMEDWAYPOINT']._serialized_start=78
  _globals['_TIMEDWAYPOINT']._serialized_end=170
  _globals['_JOINTIMPEDANCETRAJECTORYREQUEST']._serialized_start=172
  _globals['_JOINTIMPEDANCETRAJECTORYREQUEST']._serialized_end=299
  _globals['_TERMINATEREQUEST']._serialized_start=301
  _globals['_TERMINATEREQUEST']._serialized_end=319
  _globals['_BAMBOOCONTROLSERVICE']._serialized_start=322
  _globals['_BAMBOOCONTROLSERVICE']._serialized_end=577
# @@protoc_insertion_point(module_scope)
